name: Build Flutter APK

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Repositório
        uses: actions/checkout@v4

      - name: Configurar o Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Configurar o Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Instalar Dependências
        run: flutter pub get

      - name: Compilar APK
        run: flutter build apk --release

      - name: Fazer Upload do APK (Artefato)
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: build/app/outputs/flutter-apk/app-release.apk
